social_auth_steemconnect.settings:
  type: config_object
  label: 'Social Auth Steemconnect settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID (Steem app)'
    client_secret:
      type: string
      label: 'Client Secret'
